import type { Metadata } from "next";
// @ts-ignore: global stylesheet import type declarations may be missing
import "./globals.css";
import './carousel.css';

export const metadata: Metadata = {
  title: "ESS ARR ENTERPRISES",
  description: "Generated by ESS ARR ENTERPRISES",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
        
    <html
      lang="en"
      className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
