import type { Metadata } from "next";
// @ts-ignore: global stylesheet import type declarations may be missing
import "./globals.css";
import './carousel.css';


import type { Metadata } from 'next';
import { getMessages } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';
import { i18n } from '@/i18n.config';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { notFound } from "next/dist/client/components/navigation";

export const metadata: Metadata = {
  title: "ESS ARR ENTERPRISES",
  description: "Generated by ESS ARR ENTERPRISES",
};

export function generateStaticParams() {
  return i18n.locales.map((locale) => ({ locale }));
}

interface Props {
  children: React.ReactNode;
  params: { locale: string };
}


export default async function RootLayout({
  children,
  params: { locale },
}: Props) {
  if (!i18n.locales.includes(locale as any)) {
    // notFound();
  }
  //  const messages = await getMessages();
  return (
        
    <html lang={locale} dir={locale === 'ta' ? 'ltr' : 'ltr'} className={`h-full antialiased`}>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className="min-h-full flex flex-col">
             {children}
      </body>
    </html>
  );
}
